import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';

export const envSchema = z.object({
  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required (e.g. postgresql://user:pass@host:5432/db)'),
  REDIS_URL: z.string().min(1, 'REDIS_URL is required (e.g. redis://localhost:6379)'),

  NEXTAUTH_SECRET: z.string().min(16, 'NEXTAUTH_SECRET is required (min 16 characters)'),
  NEXTAUTH_URL: z.string().url().default('http://localhost:3000'),

  OPENAI_API_KEY: z.string().min(1, 'OPENAI_API_KEY is required'),
  GEMINI_API_KEY: z.string().min(1, 'GEMINI_API_KEY is required'),
  ANTHROPIC_API_KEY: z.string().min(1, 'ANTHROPIC_API_KEY is required'),
  GROQ_API_KEY: z.string().min(1, 'GROQ_API_KEY is required'),
  FAL_KEY: z.string().min(1, 'FAL_KEY is required'),
  REPLICATE_API_TOKEN: z.string().min(1, 'REPLICATE_API_TOKEN is required'),
  ELEVENLABS_API_KEY: z.string().min(1, 'ELEVENLABS_API_KEY is required'),
  DEEPGRAM_API_KEY: z.string().min(1, 'DEEPGRAM_API_KEY is required'),

  CLOUDINARY_CLOUD_NAME: z.string().min(1, 'CLOUDINARY_CLOUD_NAME is required'),
  CLOUDINARY_API_KEY: z.string().min(1, 'CLOUDINARY_API_KEY is required'),
  CLOUDINARY_API_SECRET: z.string().min(1, 'CLOUDINARY_API_SECRET is required'),

  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.string().default('3000')
});

export type Env = z.infer<typeof envSchema>;

export class EnvironmentError extends Error {
  public missingKeys: string[];
  constructor(missingKeys: string[]) {
    const formatted = missingKeys.map((k) => ` ❌  ${k}`).join('\n');
    const msg = `
================================================================================
🚨 CreatorOS ENVIRONMENT VALIDATION ERROR — APPLICATION STARTUP HALTED
================================================================================
The following required environment variables are missing or invalid:

${formatted}

Please check your .env.local file or server environment variables.
See .env.example for required keys and formats.
================================================================================
`;
    super(msg);
    this.name = 'EnvironmentError';
    this.missingKeys = missingKeys;
  }
}

export function generateEnvExample(): void {
  try {
    const exampleContent = `# ==============================================================================
# CreatorOS — Production Environment Configuration Template
# Auto-generated by src/env.ts
# Copy this file to .env.local and populate real values before starting.
# ==============================================================================

# 1. CORE INFRASTRUCTURE
DATABASE_URL="postgresql://creatoros_admin:SECURE_PASSWORD@postgres.internal:5432/creatoros_prod?sslmode=require"
REDIS_URL="redis://:SECURE_REDIS_PASSWORD@redis.internal:6379"

# 2. AUTHENTICATION
NEXTAUTH_SECRET="your-32-character-secret-key-here"
NEXTAUTH_URL="http://localhost:3000"

# 3. AI PROVIDER API KEYS
OPENAI_API_KEY="sk-proj-..."
GEMINI_API_KEY="AIzaSy..."
ANTHROPIC_API_KEY="sk-ant-..."
GROQ_API_KEY="gsk_..."
FAL_KEY="fal_..."
REPLICATE_API_TOKEN="r8_..."
ELEVENLABS_API_KEY="sk_..."
DEEPGRAM_API_KEY="..."

# 4. CLOUD STORAGE (MEDIA CDN)
CLOUDINARY_CLOUD_NAME="creatoros-cdn"
CLOUDINARY_API_KEY="123456789012345"
CLOUDINARY_API_SECRET="abcdefghijklmnopqrstuvwxyz123456"

# 5. SYSTEM ENVIRONMENT
NODE_ENV="development"
PORT="3000"
`;

    const rootDir = process.cwd();
    const examplePath = path.join(rootDir, '.env.example');
    fs.writeFileSync(examplePath, exampleContent, 'utf-8');
  } catch (err) {
    // Non-blocking file write attempt
  }
}

let cachedEnv: Env | null = null;

export function validateEnv(): Env {
  if (cachedEnv) return cachedEnv;

  generateEnvExample();

  const result = envSchema.safeParse(process.env);

  if (!result.success) {
    const missingKeys = result.error.issues.map(
      (issue) => `${issue.path.join('.')}: ${issue.message}`
    );

    if (process.env.NODE_ENV === 'production') {
      console.error(new EnvironmentError(missingKeys).message);
      if (typeof process !== 'undefined' && process.exit) {
        process.exit(1);
      }
    } else {
      console.warn(
        `\n⚠️ [CreatorOS Env Warning] Missing or unconfigured environment variables:\n${missingKeys
          .map((k) => `  - ${k}`)
          .join('\n')}\n`
      );
    }
  }

  cachedEnv = (result.success ? result.data : process.env) as unknown as Env;
  return cachedEnv;
}

export const env = validateEnv();
